const firebaseErrorMessages: Record<string, string> = {
  "auth/admin-restricted-operation": "Sorry, only administrators can perform this action.",
  "auth/argument-error": "Something went wrong with the information provided. Please try again.",
  "auth/app-not-authorized": "This app is not authorized. Please contact support.",
  "auth/app-not-installed": "Please install the app to continue.",
  "auth/captcha-check-failed": "Security verification failed. Please try again.",
  "auth/code-expired": "This verification code has expired. Please request a new one.",
  "auth/cordova-not-ready": "App is loading. Please wait and try again.",
  "auth/cors-unsupported": "Your browser doesn't support this feature. Please update your browser.",
  "auth/credential-already-in-use": "This account is already linked to another user.",
  "auth/custom-token-mismatch": "Authentication failed. Please try logging in again.",
  "auth/requires-recent-login": "For security, please log in again to continue.",
  "auth/dependent-sdk-initialized-before-auth": "Technical error occurred. Please refresh and try again.",
  "auth/dynamic-link-not-activated": "This link is not active. Please contact support.",
  "auth/email-change-needs-verification": "Please check your email and verify your new address.",
  "auth/email-already-in-use": "This email is already registered. Try signing in instead.",
  "auth/emulator-config-failed": "Configuration error. Please contact support.",
  "auth/expired-action-code": "This link has expired. Please request a new one.",
  "auth/cancelled-popup-request": "Sign-in was cancelled. Please try again.",
  "auth/internal-error": "Something went wrong on our end. Please try again later.",
  "auth/invalid-api-key": "Technical error occurred. Please contact support.",
  "auth/invalid-app-credential": "Authentication failed. Please try again.",
  "auth/invalid-app-id": "Technical error occurred. Please contact support.",
  "auth/invalid-user-token": "Your session has expired. Please log in again.",
  "auth/invalid-auth-event": "Authentication failed. Please try again.",
  "auth/invalid-cert-hash": "Security verification failed. Please try again.",
  "auth/invalid-verification-code": "The verification code is incorrect. Please check and try again.",
  "auth/invalid-continue-uri": "Invalid link. Please try again.",
  "auth/invalid-cordova-configuration": "App configuration error. Please contact support.",
  "auth/invalid-custom-token": "Authentication failed. Please try logging in again.",
  "auth/invalid-dynamic-link-domain": "Invalid link. Please contact support.",
  "auth/invalid-email": "Please enter a valid email address.",
  "auth/invalid-emulator-scheme": "Technical error occurred. Please contact support.",
  "auth/invalid-credential": "Either email or password is incorrect. Please check and try again.",
  "auth/invalid-message-payload": "Message format error. Please try again.",
  "auth/invalid-multi-factor-session": "Multi-factor authentication failed. Please try again.",
  "auth/invalid-oauth-client-id": "Authentication service error. Please contact support.",
  "auth/invalid-oauth-provider": "Sign-in method not supported. Please try another method.",
  "auth/invalid-action-code": "This reset link is invalid or expired. Please request a new one.",
  "auth/unauthorized-domain": "This domain is not authorized. Please contact support.",
  "auth/wrong-password": "Either email or password is incorrect. Please check and try again.",
  "auth/invalid-persistence-type": "Technical error occurred. Please try again.",
  "auth/invalid-phone-number": "Please enter a valid phone number.",
  "auth/invalid-provider-id": "Sign-in method error. Please try again.",
  "auth/invalid-recipient-email": "Please enter a valid email address.",
  "auth/invalid-sender": "Email sending failed. Please try again.",
  "auth/invalid-verification-id": "Verification failed. Please try again.",
  "auth/invalid-tenant-id": "Technical error occurred. Please contact support.",
  "auth/multi-factor-info-not-found": "Multi-factor authentication setup incomplete. Please contact support.",
  "auth/multi-factor-auth-required": "Additional verification required. Please complete the security check.",
  "auth/missing-android-pkg-name": "App configuration error. Please contact support.",
  "auth/missing-app-credential": "Authentication setup incomplete. Please contact support.",
  "auth/auth-domain-config-required": "Authentication not configured. Please contact support.",
  "auth/missing-verification-code": "Please enter the verification code.",
  "auth/missing-continue-uri": "Navigation error occurred. Please try again.",
  "auth/missing-iframe-start": "Loading error occurred. Please refresh and try again.",
  "auth/missing-ios-bundle-id": "App configuration error. Please contact support.",
  "auth/missing-or-invalid-nonce": "Security verification failed. Please try again.",
  "auth/missing-multi-factor-info": "Multi-factor authentication setup incomplete. Please contact support.",
  "auth/missing-multi-factor-session": "Multi-factor authentication failed. Please try again.",
  "auth/missing-phone-number": "Please enter your phone number.",
  "auth/missing-verification-id": "Verification setup failed. Please try again.",
  "auth/app-deleted": "Service is temporarily unavailable. Please try again later.",
  "auth/account-exists-with-different-credential": "An account with this email already exists. Please sign in with your original method.",
  "auth/network-request-failed": "Network connection failed. Please check your internet and try again.",
  "auth/null-user": "You are not signed in. Please log in first.",
  "auth/no-auth-event": "Authentication failed. Please try again.",
  "auth/no-such-provider": "This sign-in method is not available. Please try another method.",
  "auth/operation-not-allowed": "This sign-in method is not enabled. Please contact support.",
  "auth/operation-not-supported-in-this-environment": "This feature is not supported in your current browser. Please try a different browser.",
  "auth/popup-blocked": "Pop-up was blocked by your browser. Please allow pop-ups and try again.",
  "auth/popup-closed-by-user": "Sign-in was cancelled. Please try again.",
  "auth/provider-already-linked": "This account is already connected. Please try signing in directly.",
  "auth/quota-exceeded": "Too many requests. Please wait a moment and try again.",
  "auth/redirect-cancelled-by-user": "Sign-in was cancelled. Please try again.",
  "auth/redirect-operation-pending": "Sign-in is in progress. Please wait.",
  "auth/rejected-credential": "Sign-in was rejected. Please try again.",
  "auth/second-factor-already-in-use": "This security method is already set up.",
  "auth/maximum-second-factor-count-exceeded": "Maximum security methods reached. Please remove one to add another.",
  "auth/tenant-id-mismatch": "Account mismatch. Please contact support.",
  "auth/timeout": "Request timed out. Please try again.",
  "auth/user-token-expired": "Your session has expired. Please log in again.",
  "auth/too-many-requests": "Too many failed attempts. Please wait a few minutes and try again.",
  "auth/unauthorized-continue-uri": "Invalid redirect link. Please contact support.",
  "auth/unsupported-first-factor": "This authentication method is not supported.",
  "auth/unsupported-persistence-type": "Browser storage not supported. Please try a different browser.",
  "auth/unsupported-tenant-operation": "This operation is not supported. Please contact support.",
  "auth/unverified-email": "Please verify your email address before continuing.",
  "auth/user-cancelled": "Sign-in was cancelled. Please try again.",
  "auth/user-not-found": "No account found with this email. Please check your email or create a new account.",
  "auth/user-disabled": "This account has been disabled. Please contact support.",
  "auth/user-mismatch": "Account mismatch. Please try again.",
  "auth/user-signed-out": "You have been signed out. Please log in again.",
  "auth/weak-password": "Password is too weak. Please choose a stronger password with at least 6 characters.",
  "auth/web-storage-unsupported": "Your browser doesn't support local storage. Please enable cookies and try again.",
  "auth/already-initialized": "Authentication already set up. Please refresh and try again.",
  "auth/recaptcha-not-enabled": "Security verification not enabled. Please contact support.",
  "auth/missing-recaptcha-token": "Security verification failed. Please try again.",
  "auth/invalid-recaptcha-token": "Security verification failed. Please try again.",
  "auth/invalid-recaptcha-action": "Security verification failed. Please try again.",
  "auth/missing-client-type": "Technical error occurred. Please contact support.",
  "auth/missing-recaptcha-version": "Security verification setup incomplete. Please contact support.",
  "auth/invalid-recaptcha-version": "Security verification failed. Please try again.",
  "auth/invalid-req-type": "Invalid request. Please try again."
};

export const getFirebaseErrorMessage = (error: Error): string => {
  const errorCode = error.message.match(/auth\/[\w-]+/)?.[0];
  return errorCode ? firebaseErrorMessages[errorCode] || error.message : error.message;
};